### ISSUE TITLE
Adding LMQ support

### ISSUE THREAD

**Issue by MatP-MatP** [EnotYoyo/pysphero#11]
Hi @EnotYoyo,

Found you project quite interesting. I would like to participate on it to add LightningMcQueen support.
If you agree I can push my first branch. I am not an expert in Python, dev might be slow as I am also sniffing BT packets to find missing command.
If you do not, no pb, I’ll fork.

Thanks for what you've done

**Comment by EnotYoyo** [comment]
Hi! 
Yes. You can create pull request, I'll review and merge it.

**Comment by MatP-MatP** [comment]
Cool!

Try to push my branch, but I cannot. I guess you need to add me somehow.

remote: Permission to EnotYoyo/pysphero.git denied to MatP-MatP.
fatal: unable to access 'https://github.com/EnotYoyo/pysphero.git/': The requested URL returned error: 403

**Comment by EnotYoyo** [comment]
You must fork the repository. After, create some changes, push it into your repository and create pull request to my repository.  It's detailed [here](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) and [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

**Comment by MatP-MatP** [comment]
Thanks, not familiar with open projects. Did my first PR.

**Comment by EnotYoyo** [comment]
I close this.
