### ISSUE TITLE
Support for Force Band

### ISSUE THREAD

**Issue by H4xl0r** [EnotYoyo/pysphero#15]
Here are some details about the Force Band , maybe we can find a way to include its functions.
Ho husstle and let me know if i can help any further 

Scans : 

Android:
![Screenshot_2020-05-22-12-33-55](https://user-images.githubusercontent.com/31049432/82662046-7e9e8200-9c2d-11ea-8a09-db310d322570.jpg)
![Screenshot_2020-05-22-12-34-01](https://user-images.githubusercontent.com/31049432/82662062-84946300-9c2d-11ea-97be-9124ac011344.jpg)
![Screenshot_2020-05-22-12-34-14](https://user-images.githubusercontent.com/31049432/82662080-8a8a4400-9c2d-11ea-93ff-5967bddb33ce.jpg)
![Screenshot_2020-05-22-12-34-26](https://user-images.githubusercontent.com/31049432/82662092-8f4ef800-9c2d-11ea-8a49-9737c61986e5.jpg)
![Screenshot_2020-05-22-13-03-20](https://user-images.githubusercontent.com/31049432/82662104-91b15200-9c2d-11ea-8de7-6bbe8dce587a.jpg)

Iphone:
![IMG_0324](https://user-images.githubusercontent.com/31049432/82662113-96760600-9c2d-11ea-84e8-c0df12640c7e.PNG)
![IMG_0325](https://user-images.githubusercontent.com/31049432/82662118-983fc980-9c2d-11ea-9b8d-ce24e94e4742.PNG)

Capture File of FIRST CONNECTION of the Band.
INCLUDING the UPDATES. (Firmware & Sounds).
Initial Setup via app (Commands send Forward Backward Move to right & left ).

[force_band_initial_btsnoop_hci.zip](https://github.com/EnotYoyo/pysphero/files/4667667/force_band_initial_btsnoop_hci.zip)

**Comment by EnotYoyo** [comment]
> maybe we can find a way to include its functions 

What functions are we talking about? As far as I'm concerned, he just sends commands to sphero.

**Comment by H4xl0r** [comment]
Its able to send movment data to the app and or bot , so we could be able to read those values ?
its fully able to control the bot via hand movment.
and its able to send those movement info to the app , cause there is an in app game where you control the "App-Bot" with the band.

**Comment by EnotYoyo** [comment]
They're using similar API. You can analyze packets from pcap file and make PR if they have a specialized API :) 
The structure of the package is described [here](https://github.com/EnotYoyo/pysphero/blob/master/pysphero/packet.py#L23)

**Comment by H4xl0r** [comment]
thanks
