### ISSUE TITLE
Completing the API

### ISSUE THREAD

**Issue by Parsa-MJ** [EnotYoyo/pysphero#2]
Is there a way for you to complete the API? I mean there are a lot of commands that are not implemented in the code ( like animation, tank driving and sensors)
One other thing: sphero bolt keeps giving timeout error. have you encountered this problem before and do you have a solution for it ?

**Comment by EnotYoyo** [comment]
> sphero bolt keeps giving timeout error

When you try connect to it? 

> sensors

All sensors are implemented for Bolt. See [this](https://github.com/EnotYoyo/pysphero/blob/master/pysphero/sensor.py) and [example](https://github.com/EnotYoyo/pysphero/blob/master/examples/sensors.py).

**Comment by Parsa-MJ** [comment]
> When you try connect to 


No, actually there is no pattern for it. Sometimes it disconnects when I try to use the user_io class, sometimes when I'm using the drive_with_heading command.


and what about the other two? animations and tank driving

**Comment by EnotYoyo** [comment]
> No, actually there is no pattern for it. Sometimes it disconnects when I try to use the user_io class, sometimes when I'm using the drive_with_heading command. 

I'll try to do something about it. 

> animations and tank driving 

I don't have toys with this functions (the bolt does not seem to support). I can implement this in a separate branch, and you check it.

**Comment by Parsa-MJ** [comment]
thanks a lot mate
one more question: What is the animation_id ??

**Comment by EnotYoyo** [comment]
I haven't finished it yet. I'll add commands as functions.
I'll look for an enum with possible animations.

**Comment by EnotYoyo** [comment]
See [this](https://github.com/igbopie/spherov2.js/issues/31#issuecomment-507191703) comment. 
Animations working? Or animation_id is int (two byte)?

**Comment by EnotYoyo** [comment]
@Parsa-MJ Can you check changes?
